import { nanoid } from 'nanoid';
import type Player from '../interfaces/Player';
const db = [
  { name: 'АЛЕКСАНДР', lastName: 'ЖИРЬЯКОВ', rank: 39 },
  { name: 'АЛЕКСЕЙ', lastName: 'КИРЕЕВ', rank: 42 },
  { name: 'РУСЛАН', lastName: 'АЛЬМЯШЕВ', rank: 52 },
  { name: 'АНДРЕЙ', lastName: 'КОСТИН', rank: 37 },
  { name: 'АРКАДИЙ', lastName: 'ШАБАЛОВ', rank: 69 },
  { name: 'АНДРЕЙ', lastName: 'СМИРНОВ', rank: 65 },
  { name: 'АРСЕН', lastName: 'ДАВЫДОВ', rank: 45 },
  { name: 'АРТЕМ', lastName: 'КАРЛОВ', rank: 25 },
  { name: 'АРТЕМ', lastName: 'КИРЕЕВ', rank: 71 },
  { name: 'АРТЕМ', lastName: 'КОЗАДАЕВ', rank: 61 },
  { name: 'АРТЕМ', lastName: 'НАБОКОВ', rank: 73 },
  { name: 'АРТЕМ', lastName: 'САРЯН', rank: 24 },
  { name: 'АРТУР', lastName: 'ПОТАПОВ', rank: 77 },
  { name: 'АЛЕКСАНДР', lastName: 'БАДАЛОВ', rank: 76 },
  { name: 'МИХАИЛ', lastName: 'БИЗЕНКОВ', rank: 61 },
  { name: 'АРТЕМ', lastName: 'БОРОДИН', rank: 67 },
  { name: 'АЛЕКСАНДР', lastName: 'БУРЦЕВ', rank: 31 },
  { name: 'ВИКТОР', lastName: 'БОЮРОВ', rank: 36 },
  { name: 'ВИТАЛИЙ', lastName: 'МОГЕ', rank: 59 },
  { name: 'ВИТАЛИЙ', lastName: 'СОСИН', rank: 71 },
  { name: 'ВИТЯ', lastName: 'ГОНЧАРОВ', rank: 69 },
  { name: 'ВЛАДИМИР', lastName: 'ЕРШОВ', rank: 56 },
  { name: 'АЛЕКСАНДР', lastName: 'ВОРОНОВ', rank: 69 },
  { name: 'ГЛЕБ', lastName: 'КОЗЛОВ', rank: 51 },
  { name: 'АЛЕКСАНДР', lastName: 'ГОНЧАРОВ', rank: 52 },
  { name: 'ГРИГОРИЙ', lastName: 'БЕРДНИК', rank: 26 },
  { name: 'ДЕНИС', lastName: 'ПРУССКИЙ', rank: 74 },
  { name: 'ДМИТРИЙ', lastName: 'БАЙКОВ', rank: 51 },
  { name: 'ДМИТРИЙ', lastName: 'КАЗИОНОВ', rank: 58 },
  { name: 'ДМИТРИЙ', lastName: 'СТРАХОВ', rank: 62 },
  { name: 'ДМИТРИЙ', lastName: 'ШАКАЛИНСКИЙ', rank: 61 },
  { name: 'АЛЕКСЕЙ', lastName: 'ДУКИН', rank: 23 },
  { name: 'ЕВГЕНИЙ', lastName: 'КОНЮХОВ', rank: 39 },
  { name: 'ЕВГЕНИЙ', lastName: 'ЛАГУНЕНОК', rank: 61 },
  { name: 'СЕРГЕЙ', lastName: 'ЕРШОВ', rank: 46 },
  { name: 'ИГОРЬ', lastName: 'ЖАРОВ', rank: 27 },
  { name: 'ЕВГЕНИЙ', lastName: 'КОРЕПИН', rank: 35 },
  { name: 'СЕРГЕЙ', lastName: 'ЗАБЕЛИН', rank: 26 },
  { name: 'ВЛАДИМИР', lastName: 'ЗАЙТУНЯН', rank: 49 },
  { name: 'КОНСТАНТИН', lastName: 'СКОРИН', rank: 58 },
  { name: 'КИРИЛЛ', lastName: 'КУЗНЕЦОВ', rank: 52 },
  { name: 'НИКИТА', lastName: 'КУШНЕРОВ', rank: 71 },
  { name: 'ВЯЧЕСЛАВ', lastName: 'ЛАПТЕВ', rank: 55 },
  { name: 'АЛЕКСЕЙ', lastName: 'ЗАБОЛОТНЫЙ', rank: 62 },
  { name: 'АЛЕКСЕЙ', lastName: 'ПАНТЕЛЕЕВ', rank: 63 },
  { name: 'ЛИНАР', lastName: 'ГАЗИМОВ', rank: 71 },
  { name: 'АРТЕМ', lastName: 'ЛЮГАЕЕВ', rank: 68 },
  { name: 'МАКСИМ', lastName: 'ЛЕБЕДЕВ', rank: 68 },
  { name: 'МИХАИЛ', lastName: 'КОСТЮКОВ', rank: 69 },
  { name: 'ГЕННАДИЙ', lastName: 'МУХИН', rank: 41 },
  { name: 'ВАСИЛИЙ', lastName: 'НАСОНОВ', rank: 70 },
  { name: 'НИКИТА', lastName: 'ВИНОГРАДОВ', rank: 61 },
  { name: 'НИКИТА', lastName: 'МАЛИНОВСКИЙ', rank: 49 },
  { name: 'НИКИТА', lastName: 'СЕВРЮКОВ', rank: 59 },
  { name: 'НИКОЛАЙ', lastName: 'КОВЫЛЯЕВ', rank: 31 },
  { name: 'АЛЕКСАНДР', lastName: 'ПАНТЕЛЕЕВ', rank: 67 },
  { name: 'ПАВЕЛ', lastName: 'ЧЕРВЯКОВ', rank: 75 },
  { name: 'СЕРГЕЙ', lastName: 'ПЕТРОВИЧЕВ', rank: 49 },
  { name: 'СТАНИСЛАВ', lastName: 'РОЗДЕРИЙ', rank: 32 },
  { name: 'РОМАН', lastName: 'САБЛИН', rank: 49 },
  { name: 'РУСТАМ', lastName: 'ЖУРАЕВ', rank: 29 },
  { name: 'РОМАН', lastName: 'ТАРАСЮК', rank: 53 },
  { name: 'РУСТАМ', lastName: 'ВРАТАРЬ', rank: 78 },
  { name: 'САМВЕЛ', lastName: 'СТЕПАНЯН', rank: 49 },
  { name: 'АЛЕКСАНДР', lastName: 'СУКАЧЕВ', rank: 49 },
  { name: 'СЕМЕН', lastName: 'КОВЯЗИН', rank: 85 },
  { name: 'СЕРГЕЙ', lastName: 'БАХТИН', rank: 41 },
  { name: 'СЕРГЕЙ', lastName: 'ЧЕРНОВ', rank: 61 },
  { name: 'СЕРГЕЙ', lastName: 'РЕПЯКОВ', rank: 68 },
  { name: 'СЕРГЕЙ', lastName: 'САЛЯХОВ', rank: 69 },
  { name: 'ВИТАЛИЙ', lastName: 'СЕЧКАРЕВ', rank: 35 },
  { name: 'СТАНИСЛАВ', lastName: 'ГАЛЕЕВ', rank: 72 },
  { name: 'ТИГРАН', lastName: 'ВАРДАНЯ', rank: 73 },
  { name: 'ТИМУР', lastName: 'КВЕКСКИРИ', rank: 31 },
  { name: 'ИВАН', lastName: 'ЗИМЕНКОВ', rank: 58 },
  { name: 'АЛЕКСЕЙ', lastName: 'ЗАГОРСКИЙ', rank: 60 },
  { name: 'РОМАН', lastName: 'ФАДЕЕВ', rank: 60 },
  { name: 'ВИТАЛИЙ', lastName: 'ФЕДОТОВ', rank: 62 },
  { name: 'АЛЕКСАНДР', lastName: 'ЧУЧКАЛОВ', rank: 80 },
  { name: 'ДЕНИС', lastName: 'ЧЕГРИНЕЦ', rank: 22 },
  { name: 'ЮРА', lastName: 'ЧЕРЕПАНОВ', rank: 23 },
  { name: 'ВАСИЛИЙ', lastName: 'ШМАКОВ', rank: 71 },
  { name: 'ВЛАДИСЛАВ', lastName: 'ШУМИКОВ', rank: 23 },
  { name: 'ЭДУАРД', lastName: 'ОГАННИСЯН', rank: 75 },
  { name: 'ДЭМИС', lastName: 'КАКАБИДИС', rank: 26 },
];
// const data: Player[] = db.map((obj) => ({ ...obj, id: nanoid(4) }));

function addWinsAndId(data: Player[]): Player[] {
  return data.map((obj) => ({ ...obj, wins: Math.floor(Math.random() * 100), id: nanoid(4) }))
}

const data = addWinsAndId(db)

export default data;
